# Podfile

# Select the appropriate platform below
# Specify the minimum supported iOS version (or later) required by Kiwi
platform :ios, '5.0'
# platform :osx

#
# Some other entries might already exist in the file
# ...
#

target :NewBlacKiwiTests, :exclusive => true do
  pod 'Kiwi/XCTest'
end